[tool.black]
line-length = 90

[tool.isort]
line_length = 90
multi_line_output = 3
include_trailing_comma = true

[tool.semantic_release]
version_variable = [
"datasimulator/__init__.py:__version__"
]